name:                ascii-art-generator
version:             0.1.0.0
github:              "trinhxu2/ascii-art-generator"
license:             BSD3
author:              "Xuan Tam Trinh"
maintainer:          "trinhxu2@fit.cvut.cz"
copyright:           "2023 Xuan Tam Trinh"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ascii-art-generator#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- directory
- JuicyPixels
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ascii-art-generator:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ascii-art-generator

tests:
  ascii-art-generator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ascii-art-generator
    - hspec
    - QuickCheck
